### ISSUE TITLE
About the definition of 'step' in paper

### ISSUE THREAD

**Issue by ZyangLee** [AIDC-AI/Marco-o1#18]
Great work! I have a small question: how are the steps defined in the paper? Is it based on the newline character? (I know that a mini step consists of 32 or 64 tokens.) Also, is there any plan to open-source the sampling strategy used during inference? (The currently open-sourced models seem to still use Top-k, Top-p, and other sampling strategies.)

**Comment by Sniper970119** [comment]
Thank you for your attention. 
Yes, our definition of "step" is consistent with the paper "Let's Verify Step by Step". As for further open-source requirements, we plan to release the RL version of the model together with it.
