### ISSUE TITLE
Will Marco-o1-MCTS be open sourced in the future?

### ISSUE THREAD

**Issue by GeYuYao-hub** [AIDC-AI/Marco-o1#2]

**Comment by HuifengYin** [comment]
Yes, we will continue to release our code, models, and datasets in the future, along with updates to our Marco-01-RL (Reinforcement Learning) versions.

**Comment by HuifengYin** [comment]
> _No description provided._

Yes, we will continue to release our code, models, and datasets in the future, along with updates to our Marco-o1-RL (Reinforcement Learning) versions.
