### ISSUE TITLE
Hello, Where is  MCTS inference

### ISSUE THREAD

**Issue by Wangxiaoxiaoa** [AIDC-AI/Marco-o1#4]

**Comment by HuifengYin** [comment]
Thanks for your interests. This part has not been open-sourced yet, but we plan to gradually open-source it in the future, along with updates to the Marco-o1-RL versions. Stay tuned, please.

**Comment by gjm441** [comment]
Great work！After testing some prompts，I have several questions：
1. The Reasoning  CoT tokens "Let’s break this down step by step to ensure accuracy." and Reflection tokens "But wait, let me double check to enure I havn't miss any." in every case, how do them add to the stage? Only add same tokens in dataset?
2. The talk scripts show the inference with prefill for all stages, why don't use kvcache? Only for footprint?
3. The inference process only show selected output stages, how does the mcts and value take?
