### ISSUE TITLE
README.md (Lego set result)

### ISSUE THREAD

**Issue by jarkkop** [AIDC-AI/Marco-o1#7]
"Figure 6: Optimal Action Granularity Depends on Problem Complexity. Comparison between Marco-o1-MCTS (mini-step of 64 tokens) (left) and Marco-o1-MCTS (step) (right) on the MGSM dataset. The model with a mini-step of 64 tokens failed to find the correct answer, whereas using step-level actions enabled the model to correctly solve the problem. This highlights that we cannot draw definitive conclusions about which action strategy is superior. We believe that as the reward becomes more accurate, the larger solution space provided by MCTS will demonstrate greater potential."

To me both answers are wrong. Two sets is the correct answer in my opinion. openai-4o model agrees with me.

**Comment by HuifengYin** [comment]
Thank you for pointing out this issue. This case is intended to illustrate the limitations of the mini-step method in Marco-o1-MCTS, which is not always superior to the step version. However, we use the wrong data. We now replace it with the correct example and sincerely apologize for this mistake.
